name: project CI
on:
  - push

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: make lint-frontend
